import {
  ArrowLeftRight,
  Armchair,
  BadgePercent,
  BatteryCharging,
  Bed,
  CarFront,
  Cpu,
  Disc,
  DoorOpen,
  DownloadCloud,
  Fingerprint,
  Flag,
  Fuel,
  Gauge,
  Globe,
  Home,
  HouseWifi,
  KeyRound,
  Layers,
  MapPinned,
  Map as MapIcon,
  Maximize,
  Monitor,
  Mountain,
  Move,
  Package,
  Palette,
  PlugZap,
  Radar,
  Route,
  Shield,
  Sparkles,
  Sun,
  Tent,
  Trophy,
  Truck,
  Users,
  Volume2,
  Wallet,
  Wind,
  Wrench,
  Zap,
  type LucideProps,
} from "lucide-react";
import type { ComponentType } from "react";

const registry: Record<string, ComponentType<LucideProps>> = {
  "arrow-left-right": ArrowLeftRight,
  armchair: Armchair,
  "badge-percent": BadgePercent,
  "battery-charging": BatteryCharging,
  bed: Bed,
  "car-front": CarFront,
  cpu: Cpu,
  disc: Disc,
  "door-open": DoorOpen,
  "download-cloud": DownloadCloud,
  fingerprint: Fingerprint,
  flag: Flag,
  fuel: Fuel,
  gauge: Gauge,
  globe: Globe,
  home: Home,
  "house-wifi": HouseWifi,
  "key-round": KeyRound,
  layers: Layers,
  "map-pinned": MapPinned,
  map: MapIcon,
  maximize: Maximize,
  monitor: Monitor,
  mountain: Mountain,
  move: Move,
  package: Package,
  palette: Palette,
  "plug-zap": PlugZap,
  radar: Radar,
  route: Route,
  shield: Shield,
  sparkles: Sparkles,
  sun: Sun,
  tent: Tent,
  trophy: Trophy,
  truck: Truck,
  users: Users,
  "volume-2": Volume2,
  wallet: Wallet,
  wind: Wind,
  wrench: Wrench,
  zap: Zap,
};

export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Component = registry[name] ?? Sparkles;
  return <Component aria-hidden {...props} />;
}
